ingress:
  enabled: "true"
  nginx:
    enabled: "true"
  cce:
    autocreate: "false"
    enabled: "false"
    existing:
      class: union
  tls:
    certmanager:
      clusterIssuer: letsencrypt
      enabled: "true"
    host: rhea-demo.eu3.codbex.com
resources:
  limits:
    cpu: "4"
    memory: 6Gi
  requests:
    cpu: "1"
    memory: 1Gi
volume:
  enabled: "true"
  storage: 2Gi
  storageClassName: ssd
