apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-svc
spec:
  internalTrafficPolicy: Cluster # Service should route traffic to any node in the cluster.
  ports:
  - name: http
    port: {{ .Values.service.ports.http }}
    protocol: TCP
    targetPort: {{ .Values.service.ports.http }}
  selector:
    app: {{ .Values.name }}
  sessionAffinity: None
  {{- if eq .Values.service.type "NodePort" }}
  type: NodePort
  {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIp | quote }}
  {{- end }}
