{{- $tlsEnabled := (include "booleanToStringValue" (dict "value" .Values.ingress.tls.enabled)) | trim }}

{{- if and (eq $tlsEnabled "true") .Values.ingress.tls.crt .Values.ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secret }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
{{- end }}
