annotations:
  category: Web IDE
apiVersion: v2
name: codbex-rhea
version: 3.0.0-SNAPSHOT
appVersion: 3.0.0-SNAPSHOT
description: https://codbex.com/products/rhea
home: https://github.com/codbex/codbex-rhea
keywords:
  - documents
  - ide
  - web-ide
maintainers:
  - name: codbex
    url: https://github.com/codbex
sources:
  - https://github.com/codbex/codbex-rhea
